from HyperGuiModules.constants import *
from HyperGuiModules.utility import *
from HyperGuiModules.absorption_spec import AbsorptionSpec
from HyperGuiModules.analysis_and_form import AnalysisAndForm
from HyperGuiModules.diagram import Diagram
from HyperGuiModules.histogram import Histogram
from HyperGuiModules.new_colour import NewColour
from HyperGuiModules.original_colour import OGColour
from HyperGuiModules.source_and_output import SourceAndOutput
from HyperGuiModules.save import Save
from HyperGuiModules.recreated_colour import RecColour
from HyperGuiModules.module_listener import ModuleListener
from HyperGuiModules.original_colour_data import OGColourData
from HyperGuiModules.recreated_colour_data import RecreatedColourData
from HyperGuiModules.new_colour_data import NewColourData
from HyperGuiModules.colour import Colour
from HyperGuiModules.info import Info
from HyperGuiModules.csv_saver import CSVSaver
from HyperGuiModules.intro import Introduction
from HyperGuiModules.parameters import Parameter
from HyperGuiModules.hist_calculation import HistCalculation
from HyperGuiModules.spec_calculation import SpecCalculation
from HyperGuiModules.bp import BP
from HyperGuiModules.circle import Circle
from HyperGuiModules.rectangle import Rectangle
from HyperGuiModules.crops import crops
from HyperGuiModules.bs import BS
from HyperGuiModules.measure import Measure
from HyperGuiModules.mda import MDA
from HyperGuiModules.mda2 import MDA2
from HyperGuiModules.prediction import Prediction
from HyperGuiModules.progressions import Progressions
from HyperGuiModules.spec_invest import SpecInvest
